/*
 * This source file was generated by the Gradle 'init' task
<<<<<<< HEAD
 */ // tra
package com.example.trabajogrupo6;
// trabajo de grupo 8 de programacion
import java.util.Scanner;

public class App {
    
=======
 */
package com.example.trabajogrupo6;
 //trabajo de grupo 8 de programacion
import java.util.Scanner;

public class App {
//Meadrdo
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
    // Metodo para calcular el promedio de 3 notas
    public static double promedio(double nota1, double nota2, double nota3) {
        return (nota1 + nota2 + nota3) / 3;
    }
<<<<<<< HEAD

=======
// michael
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
    // Metodo para convertir de Celsius a Fahrenheit
    public static double celsiusAFahrenheit(double celsius) {
        return (celsius * 9.0 / 5.0) + 32;
    }

    // Metodo para convertir de Fahrenheit a Celsius
    public static double fahrenheitACelsius(double fahrenheit) {
        return (fahrenheit - 32) * 5.0 / 9.0;
    }

    // Metodo para calcular el area de un triangulo (base * altura / 2)
    public static double areaTriangulo(double base, double altura) {
        return (base * altura) / 2;
    }

<<<<<<< HEAD
    // Metodo para validar una nota entre 0 y 10 (ejercicio 3.1)
    public static double validarNota() {
        Scanner sc = new Scanner(System.in);
        double nota;
        do {
            System.out.print("Ingrese una nota entre 0 y 10: ");
            nota = sc.nextDouble();
            if (nota < 0 || nota > 10) {
                System.out.println("Nota invalida. Debe estar entre 0 y 10.");
            }
        } while (nota < 0 || nota > 10);
        return nota;
    }

=======
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int opcion;

        do {
            System.out.println("\n=== MENU PRINCIPAL ===");
            System.out.println("1. Calcular promedio de 3 notas");
            System.out.println("2. Convertir grados (Celsius <-> Fahrenheit)");
            System.out.println("3. Calcular area de un triangulo");
<<<<<<< HEAD
            System.out.println("4. Validar nota entre 0 y 10 (ejercicio 3.1)");
            System.out.println("5. Salir");
            System.out.print("Elige una opcion (1-5): ");
=======
            System.out.println("4. Salir");
            System.out.print("Elige una opcion (1-4): ");
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
            opcion = scanner.nextInt();

            switch (opcion) {
                case 1:
<<<<<<< HEAD
                    System.out.print("Ingresa la primera nota: ");
                    double n1 = scanner.nextDouble();
                    System.out.print("Ingresa la segunda nota: ");
                    double n2 = scanner.nextDouble();
                    System.out.print("Ingresa la tercera nota: ");
                    double n3 = scanner.nextDouble();
=======
                    //ingrese la primer nota
                    System.out.print("Ingresa la primera nota: ");
                    double n1 = scanner.nextDouble();
                    //ingrese la segunda nota
                    System.out.print("Ingresa la segunda nota: ");
                    double n2 = scanner.nextDouble();
                    //ingrese la tercer nota
                    System.out.print("Ingresa la tercera nota: ");
                    double n3 = scanner.nextDouble();
                    //promedio
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
                    double prom = promedio(n1, n2, n3);
                    System.out.printf("El promedio de las tres notas es: %.2f\n", prom);
                    break;

                case 2:
                    System.out.println("\n--- Conversion de Temperatura ---");
                    System.out.println("a) Convertir de Celsius a Fahrenheit");
                    System.out.println("b) Convertir de Fahrenheit a Celsius");
                    System.out.print("Elige una opcion (a/b): ");
                    char subOpcion = scanner.next().charAt(0);
<<<<<<< HEAD
                    if (subOpcion == 'a' || subOpcion == 'A') {
=======
                switch (subOpcion) {
                    case 'a':
                    case 'A':
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
                        System.out.print("Ingresa los grados Celsius: ");
                        double celsius = scanner.nextDouble();
                        double fahr = celsiusAFahrenheit(celsius);
                        System.out.printf("%.2f C equivale a %.2f F\n", celsius, fahr);
<<<<<<< HEAD
                    } else if (subOpcion == 'b' || subOpcion == 'B') {
=======
                        break;
                    case 'b':
                    case 'B':
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
                        System.out.print("Ingresa los grados Fahrenheit: ");
                        double fahrenheit = scanner.nextDouble();
                        double celsiusResult = fahrenheitACelsius(fahrenheit);
                        System.out.printf("%.2f F equivale a %.2f C\n", fahrenheit, celsiusResult);
<<<<<<< HEAD
                    } else {
                        System.out.println("Opcion no valida.");
                    }
                    break;

=======
                        break;
                    default:
                        System.out.println("Opcion no valida.");
                        break;
                }
                    break;


>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
                case 3:
                    System.out.print("Ingresa la base del triangulo: ");
                    double base = scanner.nextDouble();
                    System.out.print("Ingresa la altura del triangulo: ");
                    double altura = scanner.nextDouble();
                    double area = areaTriangulo(base, altura);
                    System.out.printf("El area del triangulo es: %.2f\n", area);
                    break;

                case 4:
<<<<<<< HEAD
                    double notaValida = validarNota();
                    System.out.printf("La nota valida registrada es: %.2f\n", notaValida);
                    break;

                case 5:
                    System.out.println("Saliendo del programa...");
=======
                    System.out.println("Saliendo del programa");
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89
                    break;

                default:
                    System.out.println("Opcion invalida. Intenta de nuevo.");
            }
<<<<<<< HEAD
        } while (opcion != 5);
=======
        } while (opcion != 4);
>>>>>>> 104d0717ae2ac33276e7fe9eada489f93bfc7b89

        scanner.close();
    }
}